# Generated by Django 3.2.16 on 2023-01-06 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everestapp', '0003_newsdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsdetail',
        ),
    ]
